### ISSUE TITLE
DOM driver should check if content loaded

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/core#301] opened 2016-05-02 16:55 UTC
Because of https://github.com/cyclejs/core/issues/200 cycle now runs synchronously and if `run` is started before content of document is loaded DOM driver will give the error.

`Given container is not a DOM element neither a selector string.`

In simplest workaround would look like:

```js
setTimeout(() => { // or window.requestAnimationFrame
  run(Main, {
    log: (m$) => m$.forEach(::console.log),
    DOM: makeDOMDriver('body')
  })
})
```

In case if string passed and DOM not ready driver could wait for it and then implement attaching to the element. Need to find out best way to implement cross-browser content load.

There is for example full cross-browser implementation:
https://github.com/dperini/ContentLoaded/blob/master/src/contentloaded.js
but seems too bulky and probably exessive for cycle.
cc @TylorS @laszlokorte

**Comment by staltz** [comment] 2016-05-02 17:16
We could do this in Cycle DOM 10

**Comment by TylorS** [comment] 2016-05-03 05:12
This is actually a duplicate of #222

**Comment by whitecolor** [comment] 2016-05-03 06:53
Yes i remembered that I've seed this issue somewhere.

**Closed** 2016-05-03 10:33 UTC
Labels: resolution: duplicate
